//This code is generated by bing copilot,, it's for control RS232 RTS pin from low to high to control shutter coild via opto-electric coupler devices.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <termios.h>

int main(int argc, char *argv[]) {
    int fd;
    struct termios options;

    fd = open("/dev/ttyUSB0", O_RDWR | O_NOCTTY | O_NDELAY);
    if (fd == -1) {
        perror("open_port: Unable to open /dev/ttyS0 - ");
        return 1;
    }

    fcntl(fd, F_SETFL, 0);

    tcgetattr(fd, &options);

    cfsetispeed(&options, B9600);
    cfsetospeed(&options, B9600);

    options.c_cflag |= (CLOCAL | CREAD);
    options.c_cflag &= ~PARENB;
    options.c_cflag &= ~CSTOPB;
    options.c_cflag &= ~CSIZE;
    options.c_cflag |= CS8;
    options.c_cflag &= ~CRTSCTS;

    options.c_lflag &= ~(ICANON | ECHO | ECHOE | ISIG);

    options.c_iflag &= ~(IXON | IXOFF | IXANY);

    options.c_oflag &= ~OPOST;

    options.c_cc[VMIN] = 0;
    options.c_cc[VTIME] = 10;

    tcsetattr(fd, TCSANOW, &options);

    char *msg = "AT+RTS=1\r\n";
    write(fd, msg, strlen(msg));  //RTS set high to trigger shutter of camera like D810/6D/R8
    usleep(100);
    char *msg2 = "AT+RTS=0\r\n";
    write(fd, msg2, strlen(msg2)); //RTS set low to disable shutter of camera

    close(fd);

    return 0;
}

